### ISSUE TITLE
missing docker-compose-no-https.yml 

### ISSUE THREAD

**Issue by worryboy** [tegonal/lasius#36]
File is missing 

as written in https://github.com/tegonal/Lasius/blob/main/README.md 
"Lasius' docker-compose.yml supports LetsEncrypt certificates out of the box, thanks to Traefik reverse proxy. If you decide to run Lasius behind another reverse proxy or SSL termination point, you can look at docker-compose-no-https.yml. However, we strongly suggest using secure connections."

But the docker-compose-no-https.yml cant be find or is linked

**Comment by toggm** [comment]
Thanks for pointing this out. We will have a look.

**Comment by toggm** [comment]
@worryboy FYI: https://github.com/tegonal/lasius-docker-compose/pull/8

**Comment by toggm** [comment]
Merged to main, therefore closing this issue
